import type { TCard } from "@/types";

export const cards: TCard[] = [
    { type: '2s', face: './src/assets/cards/2S.svg' },
    { type: '2h', face: './src/assets/cards/2H.svg' },
    { type: '2d', face: './src/assets/cards/2D.svg' },
    { type: '2c', face: './src/assets/cards/2C.svg' },
    { type: '3s', face: './src/assets/cards/3S.svg' },
    { type: '3h', face: './src/assets/cards/3H.svg' },
    { type: '3d', face: './src/assets/cards/3D.svg' },
    { type: '3c', face: './src/assets/cards/3C.svg' },
    { type: '4s', face: './src/assets/cards/4S.svg' },
    { type: '4h', face: './src/assets/cards/4H.svg' },
    { type: '4d', face: './src/assets/cards/4D.svg' },
    { type: '4c', face: './src/assets/cards/4C.svg' },
    { type: '5s', face: './src/assets/cards/5S.svg' },
    { type: '5h', face: './src/assets/cards/5H.svg' },
    { type: '5d', face: './src/assets/cards/5D.svg' },
    { type: '5c', face: './src/assets/cards/5C.svg' },
    { type: '6s', face: './src/assets/cards/6S.svg' },
    { type: '6h', face: './src/assets/cards/6H.svg' },
    { type: '6d', face: './src/assets/cards/6D.svg' },
    { type: '6c', face: './src/assets/cards/6C.svg' },
    { type: '7s', face: './src/assets/cards/7S.svg' },
    { type: '7h', face: './src/assets/cards/7H.svg' },
    { type: '7d', face: './src/assets/cards/7D.svg' },
    { type: '7c', face: './src/assets/cards/7C.svg' },
    { type: '8s', face: './src/assets/cards/8S.svg' },
    { type: '8h', face: './src/assets/cards/8H.svg' },
    { type: '8d', face: './src/assets/cards/8D.svg' },
    { type: '8c', face: './src/assets/cards/8C.svg' },
    { type: '9s', face: './src/assets/cards/9S.svg' },
    { type: '9h', face: './src/assets/cards/9H.svg' },
    { type: '9d', face: './src/assets/cards/9D.svg' },
    { type: '9c', face: './src/assets/cards/9C.svg' },
    { type: '10s', face: './src/assets/cards/TS.svg' },
    { type: '10h', face: './src/assets/cards/TH.svg' },
    { type: '10d', face: './src/assets/cards/TD.svg' },
    { type: '10c', face: './src/assets/cards/TC.svg' },
    { type: 'Js', face: './src/assets/cards/JS.svg' },
    { type: 'Jh', face: './src/assets/cards/JH.svg' },
    { type: 'Jd', face: './src/assets/cards/JD.svg' },
    { type: 'Jc', face: './src/assets/cards/JC.svg' },
    { type: 'Qs', face: './src/assets/cards/QS.svg' },
    { type: 'Qh', face: './src/assets/cards/QH.svg' },
    { type: 'Qd', face: './src/assets/cards/QD.svg' },
    { type: 'Qc', face: './src/assets/cards/QC.svg' },
    { type: 'Ks', face: './src/assets/cards/KS.svg' },
    { type: 'Kh', face: './src/assets/cards/KH.svg' },
    { type: 'Kd', face: './src/assets/cards/KD.svg' },
    { type: 'Kc', face: './src/assets/cards/KC.svg' },
    { type: 'As', face: './src/assets/cards/AS.svg' },
    { type: 'Ah', face: './src/assets/cards/AH.svg' },
    { type: 'Ad', face: './src/assets/cards/AD.svg' },
    { type: 'Ac', face: './src/assets/cards/AC.svg' }
  ];

export const hands = [
    "Royal Flush",
    "Straight Flush",
    "Four of a Kind",
    "Full House",
    "Flush",
    "Straight",
    "Three of a Kind",
    "Two Pair",
    "Pair",
    "High Card"
  ];